In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=70549f42904cd07327be871a80c98227&language=en-US&page=1')

In [3]:
response

In [9]:
df = pd.DataFrame(response.json() ['results']) [['id','title','overview','popularity','release_date','vote_count']]

In [10]:
df

,id,title,overview,popularity,release_date,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,31.0021,1994-09-23,28974
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",27.9799,1972-03-14,21903
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,15.8785,1974-12-20,13236
3,424,Schindler's List,The true story of how businessman Oskar Schind...,12.1072,1993-12-15,16747
4,389,12 Angry Men,The defense and the prosecution have rested an...,12.5978,1957-04-10,9438
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",17.9249,2001-07-20,17527
6,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,31.8521,2008-07-16,34491
7,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",7.9342,1995-10-20,4508
8,497,The Green Mile,A supernatural tale set on death row in a Sout...,15.4409,1999-12-10,18412
9,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",17.1004,2019-05-30,19545
10,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,20.8551,2003-12-17,25506
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",16.7415,1994-09-10,29136
12,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,12.7803,2016-08-26,12025
13,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,11.4232,1966-12-22,9188
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,18.8662,1994-06-23,28695
15,157336,Interstellar,The adventures of a group of explorers who mak...,48.8511,2014-11-05,37974
16,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",11.6524,1990-09-12,13675
17,346,Seven Samurai,A samurai answers a village's request for prot...,7.9654,1954-04-26,3996
18,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",0.0103,1988-04-16,6130
19,637,Life Is Beautiful,A touching story of an Italian book seller of ...,8.1371,1997-12-20,13566

In [11]:
df.to_csv('movies.csv')